apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: auth
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgresql-db:5432/keycloak
  KC_REALM_NAME: kubeflow
  KC_LOG_LEVEL: INFO
  KC_HEALTH_ENABLED: "true"
  KC_HTTP_RELATIVE_PATH: auth
  KC_HTTP_ENABLED: "true"
  ## Dev
  #KC_HOSTNAME_URL: "https://keycloak.ai.inesdata.upm/auth"
  #KC_HOSTNAME_ADMIN_URL: "https://keycloak-admin.ai.inesdata.upm/auth"
  ## Prod
  KC_HOSTNAME_URL: "https://keycloak.ai.inesdata-project.eu/auth"
  KC_HOSTNAME_ADMIN_URL: "https://keycloak-admin.ai.inesdata.upm/auth"
  KC_HTTPS_CERTIFICATE_FILE: "/etc/x509/https/tls.crt"
  KC_HTTPS_CERTIFICATE_KEY_FILE: "/etc/x509/https/tls.key"
  KC_PROXY_HEADERS: "forwarded"
