apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: auth
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            ## Internal
            #- keycloak.ai.inesdata.upm
            ## External
            - keycloak.ai.inesdata-project.eu
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.2
          args: ["start", "--health-enabled=true"]
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: keycloak-secret
            - configMapRef:
                name: keycloak-config
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          volumeMounts:
            - name: keycloak-cert
              mountPath: /etc/x509/https
              readOnly: true
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 3Gi
              cpu: 3
          livenessProbe:
            httpGet:
              path: /auth/health/live
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /auth/health/ready
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 10
      volumes:
        - name: keycloak-cert
          secret:
            secretName: keycloak-cert
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
