apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: auth
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.2
          args: ["start", "--health-enabled=true"]
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: keycloak-secret
          ports:
            - name: http
              containerPort: 8080
#          readinessProbe:
#            httpGet:
#              path: /realms/master
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            failureThreshold: 5
      # Change with your secret for pull Docker images from private Registry
      # https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
      imagePullSecrets:
        - name: regcred