apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
  - namespace.yaml
  - postgres.yaml
  - config-map.yaml
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: keycloak-secret
    type: Opaque
    envs:
      - secret_params.env
