apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: auth
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgresql-db:5432/keycloak
  KC_DB_USERNAME: keycloak
  KC_DB_PASSWORD: keycloak
  KC_REALM_NAME: kubeflow
  KC_LOG_LEVEL: INFO
  KC_HEALTH_ENABLED: "true"
  KC_HTTP_RELATIVE_PATH: /auth
  KC_HOSTNAME_STRICT: "false"
  KC_PROXY: edge
