apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: auth
spec:
  selector:
    app: keycloak
  clusterIP: 10.96.7.196
  ports:
    - name: http
      port: 8080
      targetPort: 8080
