# This is a kustomization package used to allow kfctl to
# bootstrap a profile for the user running kfctl.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - profile-instance.yaml
configMapGenerator:
  - name: default-install-config
    envs:
      - params.env
vars:
  # These vars are used for substituing in the parameters from the config map
  # into the Profiles custom resource.
  - name: user
    objref:
      kind: ConfigMap
      name: default-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.user
  - name: profile-name
    objref:
      kind: ConfigMap
      name: default-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.profile-name
  - name: cpu
    objref:
      kind: ConfigMap
      name: default-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.cpu
  - name: memory
    objref:
      kind: ConfigMap
      name: default-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.memory
  - name: gpu
    objref:
      kind: ConfigMap
      name: default-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.gpu
  - name: mig-gpu-20g
    objref:
      kind: ConfigMap
      name: default-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.mig-gpu-20g
  #- name: mig-gpu-5g
  #  objref:
  #    kind: ConfigMap
  #    name: default-install-config
  #    apiVersion: v1
  #  fieldref:
  #    fieldpath: data.mig-gpu-5g
  - name: storage
    objref:
      kind: ConfigMap
      name: default-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.storage
configurations:
  - params.yaml
