apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: ${PROFILE_NAME}
spec:
  limits:
    - default:
        cpu: "10m"
        memory: "10Mi"
      defaultRequest:
        cpu: "10m"
        memory: "10Mi"
      max:
        cpu: ${CPU}
        memory: ${MEMORY}
      min:
        cpu: "10m"
        memory: "10Mi"
      type: Container
