apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: $(profile-name)
spec:
  limits:
  - default:
      cpu: '10m'
      memory: '10Mi'
    defaultRequest:
      cpu: '10m'
      memory: '10Mi'
    max:
      cpu: $(cpu)
      memory: $(memory)
    min:
      cpu: '10m'
      memory: '10Mi'
    type: Container