varReference:
- path: spec/owner/name
  kind: Profile
- path: spec/resourceQuotaSpec/hard/cpu
  kind: Profile
- path: spec/resourceQuotaSpec/hard/memory
  kind: Profile
- path: spec/resourceQuotaSpec/hard/requests.nvidia.com\/gpu
  kind: Profile
- path: spec/resourceQuotaSpec/hard/requests.nvidia.com\/mig-3g.20gb
  kind: Profile
#- path: spec/resourceQuotaSpec/hard/requests.nvidia.com\/mig-1g.5gb
#  kind: Profile
- path: spec/resourceQuotaSpec/hard/requests.storage
  kind: Profile
- path: spec/limits/default/cpu
  kind: LimitRange
- path: spec/limits/default/memory
  kind: LimitRange
- path: spec/limits/defaultRequest/cpu
  kind: LimitRange
- path: spec/limits/defaultRequest/memory
  kind: LimitRange
- path: spec/limits/max/cpu
  kind: LimitRange
- path: spec/limits/max/memory
  kind: LimitRange
- path: spec/limits/min/cpu
  kind: LimitRange
- path: spec/limits/min/memory
  kind: LimitRange
- path: metadata/namespace
  kind: LimitRange
- path: metadata/name
  kind: Profile
- path: metadata/name
  kind: Namespace
- path: metadata/namespace
  kind: PodDefault
