apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: $(profile-name)
spec:
  owner:
    kind: User
    name: $(user)
  resourceQuotaSpec: # resource quota can be set optionally
    hard:
      cpu: $(cpu)
      memory: $(memory)
      requests.nvidia.com/gpu: $(gpu)
      requests.nvidia.com/mig-3g.20gb: $(mig-gpu-20g)
      #      requests.nvidia.com/mig-1g.5gb: $(mig-gpu-5g)
      requests.storage: $(storage)
