apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: $(profile-name)
spec:
  owner:
    kind: User
    name: $(user)
  resourceQuotaSpec: # resource quota can be set optionally
    hard:
      cpu: "8"
      memory: "16Gi"
      requests.nvidia.com/gpu: "0"
      requests.nvidia.com/mig-3g.20gb: "0"
      persistentvolumeclaims: "2"
      requests.storage: "100Gi"