apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: keycloak-cluster-issuer
  namespace: auth
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: auth
spec:
  secretName: keycloak-cert
  isCA: true
  usages:
    - server auth
  commonName: "keycloak.kubeflow.inesdata.upm"
  dnsNames:
    - "keycloak.kubeflow.inesdata.upm"
    - "keycloak-admin.kubeflow.inesdata.upm"
    - "keycloak.ai.inesdata-project.eu"
  issuerRef:
    name: keycloak-cluster-issuer
    kind: ClusterIssuer
