apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: keycloak-cluster-issuer
  namespace: auth
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: auth
spec:
  secretName: keycloak-cert
  isCA: true
  usages:
    - server auth
  ## Internal
  #commonName: "keycloak.ai.inesdata.upm"
  ## External
  commonName: "keycloak.ai.inesdata-project.eu"
  dnsNames:
    - "keycloak-admin.ai.inesdata.upm"
    ## Internal
    #- "keycloak.ai.inesdata.upm"
    ## External
    - "keycloak.ai.inesdata-project.eu"
  issuerRef:
    name: keycloak-cluster-issuer
    kind: ClusterIssuer
