apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  type: ClusterIP
  selector:
    app: authservice
  ports:
    - port: 8080
      name: http-authservice
      targetPort: http-api
    - name: http-web
      port: 8082
      protocol: TCP
      targetPort: http-web
  publishNotReadyAddresses: true
