apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeflow-ingress
  namespace: istio-system
  annotations:
    nginx.org/websocket-services: "istio-ingressgateway"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.org/client-max-body-size: "0"
spec:
  ingressClassName: nginx
  rules:
    - host: dashboard.kubeflow.inesdata.upm
      http:
        paths:
          - backend:
              service:
                name: istio-ingressgateway
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: kubeflow.ai.inesdata-project.eu
      http:
        paths:
          - backend:
              service:
                name: istio-ingressgateway
                port:
                  number: 80
            path: /
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: auth
  annotations:
    cert-manager.io/cluster-issuer: "keycloak-cluster-issuer"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "512k"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - keycloak.kubeflow.inesdata.upm
        - keycloak-admin.kubeflow.inesdata.upm
        - keycloak.ai.inesdata-project.eu
      secretName: keycloak-cert
  rules:
    ## Internal access
    # Keycloak
    - host: keycloak.kubeflow.inesdata.upm
      http:
        paths:
          - backend:
              service:
                name: keycloak
                port:
                  number: 8080
            path: /auth
            pathType: Prefix
    # Admin panel
    - host: keycloak-admin.kubeflow.inesdata.upm
      http:
        paths:
          - backend:
              service:
                name: keycloak
                port:
                  number: 8080
            path: /auth
            pathType: Prefix
    ## External access
    # Keycloak
    - host: keycloak.ai.inesdata-project.eu
      http:
        paths:
          - backend:
              service:
                name: keycloak
                port:
                  number: 8080
            path: /auth
            pathType: Prefix
    # Keycloak
    - host: keycloak-admin.ai.inesdata-project.eu
      http:
        paths:
          - backend:
              service:
                name: keycloak
                port:
                  number: 8080
            path: /auth
            pathType: Prefix
