apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

# Cert-Manager
# Istio
# OIDC Authservice
# Keycloak
# KNative
# Kubeflow namespace
# Kubeflow Roles
# Kubeflow Istio Resources


# Kubeflow Pipelines
# Central Dashboard
# Admission Webhook
# Jupyter Web App
# Notebook Controller
# Profiles + KFAM
# PVC Viewer
# Volumes Web App
# User namespace


# KServe
resources:
- ./common/cert-manager/cert-manager/base
- ./common/cert-manager/kubeflow-issuer/base
- ./common/istio/istio-crds/base
- ./common/istio/istio-namespace/base
- ./common/istio/istio-install/base
- ./common/oidc-client/oidc-authservice/base
- ./common/keycloak/overlays/istio
- ./common/knative/knative-serving/overlays/gateways
- ./common/knative/knative-eventing/base
- ./common/istio/cluster-local-gateway/base
- ./common/kubeflow-namespace/base
- ./common/kubeflow-roles/base
- ./common/istio/kubeflow-istio-resources/base
- ./apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
- ./apps/centraldashboard/upstream/overlays/kserve
- ./apps/admission-webhook/upstream/overlays/cert-manager
- ./apps/jupyter/jupyter-web-app/upstream/overlays/istio
- ./apps/jupyter/notebook-controller/upstream/overlays/kubeflow
- ./apps/profiles/upstream/overlays/kubeflow
- ./apps/pvcviewer-controller/upstream/base/
- ./apps/volumes-web-app/upstream/overlays/istio
- ./common/user-namespace/base
- ./contrib/kserve/kserve
- ./contrib/kserve/models-web-app/overlays/kubeflow
