apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-certs-script
  namespace: sync-certs
data:
  sync-secret.sh: |
    #!/bin/sh

    # Obtener el valor del certificado (tls.crt) del secret en el namespace auth
    auth_cert=$(kubectl get secret keycloak-cert -n auth -o json | jq -r '.data["tls.crt"]')

    # Intentar obtener el certificado (tls.crt) del secret en el namespace istio-system
    istio_cert=$(kubectl get secret keycloak-cert -n istio-system -o json 2>/dev/null | jq -r '.data["tls.crt"]')

    # Variable para determinar si se debe sincronizar
    sync_needed=false

    if [ -z "$istio_cert" ]; then
      echo "No se encontró el certificado en istio-system, se procederá a sincronizarlo."
      sync_needed=true
    else
      # Comparar los certificados obtenidos
      if [ "$auth_cert" = "$istio_cert" ]; then
        echo "Los certificados son iguales, no se realizará ninguna acción."
      else
        echo "Los certificados difieren, se procederá a sincronizar."
        sync_needed=true
      fi
    fi

    # Si se detecta que se necesita la sincronización, actualizamos el secret y reiniciamos el pod
    if [ "$sync_needed" = true ]; then
      # Sincronizar el secret desde auth a istio-system
      kubectl get secret keycloak-cert -n auth -o json | \
        jq 'del(.metadata.namespace, .metadata.creationTimestamp, .metadata.resourceVersion, .metadata.selfLink, .metadata.uid, .metadata.annotations)' | \
        kubectl apply -n istio-system -f -
      
      # Reiniciar el OIDC para que cargue la nueva configuración
      kubectl delete pod oidc-authservice-0 -n istio-system
    fi

