apiVersion: v1
kind: ServiceAccount
metadata:
  name: sync-certs-sa
  namespace: sync-certs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sync-certs-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sync-certs-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sync-certs-role
subjects:
- kind: ServiceAccount
  name: sync-certs-sa
  namespace: sync-certs
